HOST: http://www.processmaker.com/api/1.0/{workspace}/
--- ProcessMaker "Michelangelo" API v1 ---
---
 Welcome to ProcessMaker API documentation.
 All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)

 *(This API is under development yet, please wait for a final v1 release)*
---

--
Status & Error Codes
This section standardizes the status & error codes used in our system. If it isn't defined here, it MUST NOT be returned.

#Success
    200 | Ok                 | Success, payload accompanies response if appropriate.
    201 | Created            | Success, the requested resource was created.
    202 | Accepted           | Success, but results are not immediately available.
    204 | No Content         | Success, no response payload.
    207 | Partial Success    | Used for mult-part requests where some items may result in different statuses.

#Failure
    400 | Invalid Request    | One or more parameters were invalid.
    401 | Unauthorized       | Unauthorized; missing API key.
    402 | Request Failed     | Request failed; insufficient permission.
    403 | Forbidden          | Request rejected; invalid API key.
    404 | Not Found          | Some object in the request was invalid.
    405 | UNUSED             | Method not allowed.
    406 | Not Acceptable     | Not acceptable; use application/json; charset=utf-8
    408 | UNUSED             | Request Timeout.
    409 | UNUSED             | Conflict.
    410 | UNUSED             | Gone.
    413 | Request Too Large  | Request too large; send <= 100 messages per batch.
    415 | Request Unparsable | Request unparsable; check POST JSON.
    422 | Request Rejected   | Request rejected; could not send message to recipient.

#Error
    500 | Internal Server Error  | Internal service error, ALL HELL IS BREAKING LOOSE! AAAAAAAAHHHHHH!!!!!
    501 | Not Implemented        | Method or service not yet implemented.
    503 | Service Unavailable
    507 | UNUSED                 | Insufficient Storage 


--

--
Failure Response

Failure response will be returned when a application failure is present

##Example
###Request: 
    > GET /api/1.0/{workspace}/project/{invalid-uid}
###Response:
    < 400
    < Content-Type: application/json
    {  
        "code": 32,
        "message": "project id invalid",
        "errors" : [
            {        
                "workspace": "workflow",
                "method": "POST",
                "dev_message": "The uid is invalid because the database does not have a record with that index",
                "more_info" : "http://processmaker.com/errors-code/43438"
            },
        ]
    }

--

--
Processmaker OAuth2

#1. Registering an Application
First Login  on ProcessMaker and go to the following url:

    Link: http://<your-pm-server>/sys<your-workspace>/en/neoclassic/oauth2/register
Register your application and get your Client ID and Client Secret credentials.

#2. Request Authorization for an application

Authorize your app, with following url:

    Link: http://<your-pm-server>/sys<your-workspace>/en/neoclassic/oauth2/authorize?response_type=code&client_id={your-client-d}&scope=view_processes%20edit_processes

Required Parameters | Description   | Valid Values
------------------- |:------------- |:---------------------------
response_type       | Response type | **code**
client_id           | The Client ID | 
scope               | API Scope     | **view_process**, **edit_process**

>***Note.-*** Scope value can have multiples values separated by a single space or its url encode equivalent %20.

When url above is requested, it will redirect to the User Login and after that a authorization screen will be displayed to authorize the application.

After the User authorize the application, ProcessMaker will redirect to "URL Redirect (Callback)" of the application.

#3. Getting **Access Token**
![Alt text](http://upload.wikimedia.org/wikipedia/commons/7/71/Authentication_flow_for_the_Sent.ly_Plus_API.png "Optional title")

--

Getting Access Token using the **Authorization Code**

Required Parameters | Description
:------------------ | :------------
grant_type          | Grant type to use, currently we just implementing **authorization_code**
code                | Authorization code.   

POST /token
> Authorization: Basic eC1wbS1sb2NhbC1jbGllbnQ6MTc5YWQ0NWM2Y2UyY2I5N2NmMTAyOWUyMTIwNDZlODE=
> Content-Type: application/json
{
    "grant_type": "authorization_code",
    "code": "b4b1b216ab95ef3437f9c68e6c2bf8f7224fd284"
}
< 200
< Content-Type: application/json
{
    "access_token": "265a378d39998ecfe723dbf04e621c4944950f96",
    "expires_in": 3600,
    "token_type": "bearer",
    "scope": "view_processes edit_processes",
    "refresh_token": "9ed17b93a0731e218a3a85b52974afaf23838337"
}

Getting Access Token using the **Refresh Token**

Required Parameters  | Description
:------------------- | :----------------
grant_type           | Grant type, to retrieve a new access token use: **refresh_token**
refresh_token        | The refresh token.



POST /token
> Authorization: Basic eC1wbS1sb2NhbC1jbGllbnQ6MTc5YWQ0NWM2Y2UyY2I5N2NmMTAyOWUyMTIwNDZlODE=
> Content-Type: application/json
{
    "grant_type": "authorization_code",
    "refresh_token": "c54adcfdb1d99d10be3be3b77ec32a2e402ef7e3"
}
< 200
< Content-Type: application/json
{
    "access_token": "265a378d39998ecfe723dbf04e621c4944950f96",
    "expires_in": 3600,
    "token_type": "bearer",
    "scope": "view_processes edit_processes",
    "refresh_token": "9ed17b93a0731e218a3a85b52974afaf23838337"
}


--
Project Resources
The following is a section of resources related to ProcessMaker Process Definition
--

Get a list of `projects`
GET /projects
< 200
< Content-Type: application/json
[
    {
    "prj_uid" : "8061532405176da5242da84006421863",
    "prj_name" : "Sample Project",
    "prj_description" : "sample desc",
    "diagrams":
        [
            {
                "diag_uid": "a5242da840064218638061532405176",
                "laneset": [],
                "lanes": [],
                "activities":
                    [
                        {
                            "act_uid": "278251934525d8ebbfb8565093239226",
                            "act_name": "Task",
                            "act_type": "EMPTY",
                            "bou_x": 235,
                            "bou_y": 280,
                            "bou_width": 120,
                            "bou_height": 60,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        },
                        {
                            "act_uid": "326395445525d8ec1fb8768023935580",
                            "act_name": "Task",
                            "act_type": "EMPTY",
                            "bou_x":611,
                            "bou_y":170,
                            "bou_width":120,
                            "bou_height":60,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        },
                        {
                            "act_uid": "588707952525d8ec4fb88c2038077596",
                            "act_name": "Task",
                            "act_type": "EMPTY",
                            "bou_x":630,
                            "bou_y":404,
                            "bou_width":120,
                            "bou_height":60,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        }
                    ],
                "events":
                    [
                        {
                            "evn_uid": "960500897525d8eb8fb84b4013700338",
                            "evn_name":null,
                            "evn_type":"",
                            "evn_marker":"",
                            "evn_is_interrupting":true,
                            "evn_attached_to":null,
                            "evn_cancel_activity":false,
                            "evn_activity_ref":null,
                            "evn_wait_for_completion":false,
                            "evn_error_name":null,
                            "evn_error_code":null,
                            "evn_escalation_name":null,
                            "evn_escalation_code":null,
                            "evn_condition":null,
                            "evn_message":null,
                            "evn_operation_name":null,
                            "evn_operation_implementation_ref":null,
                            "evn_time_date":null,
                            "evn_time_cycle":null,
                            "evn_time_duration":null,
                            "evn_behavior":"",
                            "bou_x":87,
                            "bou_y":261,
                            "bou_width":33,
                            "bou_height":33,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        },
                        {
                            "evn_uid": "941908090525d8ec7fb8a07093841901",
                            "evn_name":null,
                            "evn_type":"",
                            "evn_marker":"",
                            "evn_is_interrupting":true,
                            "evn_attached_to":null,
                            "evn_cancel_activity":false,
                            "evn_activity_ref":null,
                            "evn_wait_for_completion":false,
                            "evn_error_name":null,
                            "evn_error_code":null,
                            "evn_escalation_name":null,
                            "evn_escalation_code":null,
                            "evn_condition":null,
                            "evn_message":null,
                            "evn_operation_name":null,
                            "evn_operation_implementation_ref":null,
                            "evn_time_date":null,
                            "evn_time_cycle":null,
                            "evn_time_duration":null,
                            "evn_behavior":"",
                            "bou_x":903,
                            "bou_y":303,
                            "bou_width":33,
                            "bou_height":33,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        }
                    ],
                "gateways":
                    [
                        {
                            "gat_uid": "403208160525d8ebefb86a0059076243",
                            "gat_name":null,
                            "bou_x":481,
                            "bou_y":306,
                            "bou_width":45,
                            "bou_height":45,
                            "bou_container": "bpmnDiagram",
                            "bou_element_id": "pm_canvas"
                        }
                    ],
                "flows":
                    [
                        {
                            "flo_uid": "724155752525d8ec9fb8de2003171877",
                            "flo_type": "SEQUENCE",
                            "flo_name":null,
                            "flo_element_origin": "960500897525d8eb8fb84b4013700338",
                            "flo_element_origin_type": "bpmnEvent",
                            "flo_element_dest": "278251934525d8ebbfb8565093239226",
                            "flo_element_dest_type": "bpmnActivity",
                            "flo_is_inmediate":true,
                            "flo_condition":null,
                            "flo_state":
                                [
                                    {"x":104,"y":261},
                                    {"x":104,"y":241},
                                    {"x":168,"y":241},
                                    {"x":168,"y":309},
                                    {"x":233,"y":309}
                                ]
                        },
                        {
                            "flo_uid": "891030650525d8eccfb92c9033321037",
                            "flo_type": "SEQUENCE",
                            "flo_name":null,
                            "flo_element_origin": "278251934525d8ebbfb8565093239226",
                            "flo_element_origin_type": "bpmnActivity",
                            "flo_element_dest": "403208160525d8ebefb86a0059076243",
                            "flo_element_dest_type": "bpmnGateway",
                            "flo_is_inmediate":true,
                            "flo_condition":null,
                            "flo_state":
                                [
                                    {"x":294,"y":278},
                                    {"x":294,"y":258},
                                    {"x":387,"y":258},
                                    {"x":387,"y":329},
                                    {"x":481,"y":329}
                                ]
                        },
                        {
                            "flo_uid": "785603906525d8ecffb9879037717215",
                            "flo_type": "SEQUENCE",
                            "flo_name":null,
                            "flo_element_origin": "403208160525d8ebefb86a0059076243",
                            "flo_element_origin_type": "bpmnGateway",
                            "flo_element_dest": "326395445525d8ec1fb8768023935580",
                            "flo_element_dest_type": "bpmnActivity",
                            "flo_is_inmediate":true,
                            "flo_condition":null,
                            "flo_state":
                                [
                                    {"x":504,"y":306},
                                    {"x":504,"y":199},
                                    {"x":609,"y":199}
                                ]
                        },
                        {
                            "flo_uid": "531073186525d8ed2fb9d51058983227",
                            "flo_type": "SEQUENCE",
                            "flo_name":null,
                            "flo_element_dest": "588707952525d8ec4fb88c2038077596",
                            "flo_element_origin": "403208160525d8ebefb86a0059076243",
                            "flo_element_origin_type": "bpmnGateway",
                            "flo_element_dest_type": "bpmnActivity",
                            "flo_is_inmediate":true,
                            "flo_condition":null,
                            "flo_state":
                                [
                                    {"x":481,"y":329},
                                    {"x":461,"y":329},
                                    {"x":461,"y":433},
                                    {"x":628,"y":433}
                                ]
                        }
                    ],
                "artifacts": []
            }
        ]
    }
]

Get a single `project`
GET /project/{prj_uid}
< 200
< Content-Type: application/json
{
    "prj_uid" : "8061532405176da5242da84006421863",
    "prj_name" : "Sample Project",
    "prj_description" : "sample desc",
    "diagrams":
    [
        {
            "diag_uid": "a5242da840064218638061532405176",
            "laneset": [],
            "lanes": [],
            "activities":
                [
                    {
                        "act_uid": "278251934525d8ebbfb8565093239226",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x": 235,
                        "bou_y": 280,
                        "bou_width": 120,
                        "bou_height": 60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "326395445525d8ec1fb8768023935580",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":611,
                        "bou_y":170,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "588707952525d8ec4fb88c2038077596",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":630,
                        "bou_y":404,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "events":
                [
                    {
                        "evn_uid": "960500897525d8eb8fb84b4013700338",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":87,
                        "bou_y":261,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "evn_uid": "941908090525d8ec7fb8a07093841901",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":903,
                        "bou_y":303,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "gateways":
                [
                    {
                        "gat_uid": "403208160525d8ebefb86a0059076243",
                        "gat_name":null,
                        "bou_x":481,
                        "bou_y":306,
                        "bou_width":45,
                        "bou_height":45,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "flows":
                [
                    {
                        "flo_uid": "724155752525d8ec9fb8de2003171877",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "960500897525d8eb8fb84b4013700338",
                        "flo_element_origin_type": "bpmnEvent",
                        "flo_element_dest": "278251934525d8ebbfb8565093239226",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":104,"y":261},
                                {"x":104,"y":241},
                                {"x":168,"y":241},
                                {"x":168,"y":309},
                                {"x":233,"y":309}
                            ]
                    },
                    {
                        "flo_uid": "891030650525d8eccfb92c9033321037",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "278251934525d8ebbfb8565093239226",
                        "flo_element_origin_type": "bpmnActivity",
                        "flo_element_dest": "403208160525d8ebefb86a0059076243",
                        "flo_element_dest_type": "bpmnGateway",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":294,"y":278},
                                {"x":294,"y":258},
                                {"x":387,"y":258},
                                {"x":387,"y":329},
                                {"x":481,"y":329}
                            ]
                    },
                    {
                        "flo_uid": "785603906525d8ecffb9879037717215",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest": "326395445525d8ec1fb8768023935580",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":504,"y":306},
                                {"x":504,"y":199},
                                {"x":609,"y":199}
                            ]
                    },
                    {
                        "flo_uid": "531073186525d8ed2fb9d51058983227",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_dest": "588707952525d8ec4fb88c2038077596",
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":481,"y":329},
                                {"x":461,"y":329},
                                {"x":461,"y":433},
                                {"x":628,"y":433}
                            ]
                    }
                ],
            "artifacts": []
        }
    ]
}


Create a new `project`
POST /project
> Content-Type: application/json
{
    "prj_uid" : "8061532405176da5242da84006421863",
    "prj_name" : "Sample Project",
    "prj_description" : "sample desc",
    "diagrams":
    [
        {
            "diag_uid": "a5242da840064218638061532405176",
            "laneset": [],
            "lanes": [],
            "activities":
                [
                    {
                        "act_uid": "278251934525d8ebbfb8565093239226",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x": 235,
                        "bou_y": 280,
                        "bou_width": 120,
                        "bou_height": 60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "326395445525d8ec1fb8768023935580",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":611,
                        "bou_y":170,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "588707952525d8ec4fb88c2038077596",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":630,
                        "bou_y":404,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "events":
                [
                    {
                        "evn_uid": "960500897525d8eb8fb84b4013700338",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":87,
                        "bou_y":261,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "evn_uid": "941908090525d8ec7fb8a07093841901",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":903,
                        "bou_y":303,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "gateways":
                [
                    {
                        "gat_uid": "403208160525d8ebefb86a0059076243",
                        "gat_name":null,
                        "bou_x":481,
                        "bou_y":306,
                        "bou_width":45,
                        "bou_height":45,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "flows":
                [
                    {
                        "flo_uid": "724155752525d8ec9fb8de2003171877",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "960500897525d8eb8fb84b4013700338",
                        "flo_element_origin_type": "bpmnEvent",
                        "flo_element_dest": "278251934525d8ebbfb8565093239226",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":104,"y":261},
                                {"x":104,"y":241},
                                {"x":168,"y":241},
                                {"x":168,"y":309},
                                {"x":233,"y":309}
                            ]
                    },
                    {
                        "flo_uid": "891030650525d8eccfb92c9033321037",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "278251934525d8ebbfb8565093239226",
                        "flo_element_origin_type": "bpmnActivity",
                        "flo_element_dest": "403208160525d8ebefb86a0059076243",
                        "flo_element_dest_type": "bpmnGateway",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":294,"y":278},
                                {"x":294,"y":258},
                                {"x":387,"y":258},
                                {"x":387,"y":329},
                                {"x":481,"y":329}
                            ]
                    },
                    {
                        "flo_uid": "785603906525d8ecffb9879037717215",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest": "326395445525d8ec1fb8768023935580",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":504,"y":306},
                                {"x":504,"y":199},
                                {"x":609,"y":199}
                            ]
                    },
                    {
                        "flo_uid": "531073186525d8ed2fb9d51058983227",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_dest": "588707952525d8ec4fb88c2038077596",
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":481,"y":329},
                                {"x":461,"y":329},
                                {"x":461,"y":433},
                                {"x":628,"y":433}
                            ]
                    }
                ],
            "artifacts": []
        }
    ]
}
< 201
< Content-Type: application/json
[
    {
        "old_uid": "a5242da840064218638061532405176",
        "new_uid": "146756055527ab40fca1f61040187521",
        "object": "diagram",
    },
    {
        "old_uid":"278251934525d8ebbfb8565093239226", 
        "new_uid": "154619055527bbbbea27110004783861", 
        "object":"activity"
    },
    {
        "old_uid":"326395445525d8ec1fb8768023935580", 
        "new_uid": "44313230351ae0168e63669021546957", 
        "object":"activity"
    },
    {
        "old_uid":"588707952525d8ec4fb88c2038077596", 
        "new_uid": "44313230351ae0168e63669021546957", 
        "object":"activity"
    },
    {
        "old_uid":"960500897525d8eb8fb84b4013700338", 
        "new_uid": "157493645523b4c00067b67020029802",
        "object": "event"
    },
    {
        "old_uid":"941908090525d8ec7fb8a07093841901", 
        "new_uid": "55151892151af5557de5414010032345",
        "object": "event"
    },
    {
        "old_uid":"403208160525d8ebefb86a0059076243", 
        "new_uid": "60108982451ae53bc5786b3013937849",
        "object": "gateway"
    },
    {
        "old_uid":"724155752525d8ec9fb8de2003171877", 
        "new_uid": "87474948551af4835e2cd45025472854",
        "object": "flow"
    },
    {
        "old_uid":"891030650525d8eccfb92c9033321037", 
        "new_uid": "55151892151af5557de5414010032345",
        "object": "flow"
    },
    {
        "old_uid":"785603906525d8ecffb9879037717215", 
        "new_uid": "88931079151af479d543650091554690",
        "object": "flow"
    },
    {
        "old_uid":"531073186525d8ed2fb9d51058983227", 
        "new_uid": "9357304135242e2c7da7a59001869953",
        "object": "flow"
    }
]


Update a `project`
PUT /project/{prj_uid}
> Content-Type: application/json
{
    "prj_uid" : "8061532405176da5242da84006421863",
    "prj_name" : "Sample Project",
    "prj_description" : "sample desc",
    "diagrams":
    [
        {
            "diag_uid": "a5242da840064218638061532405176",
            "laneset": [],
            "lanes": [],
            "activities":
                [
                    {
                        "act_uid": "278251934525d8ebbfb8565093239226",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x": 235,
                        "bou_y": 280,
                        "bou_width": 120,
                        "bou_height": 60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "326395445525d8ec1fb8768023935580",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":611,
                        "bou_y":170,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "act_uid": "588707952525d8ec4fb88c2038077596",
                        "act_name": "Task",
                        "act_type": "EMPTY",
                        "bou_x":630,
                        "bou_y":404,
                        "bou_width":120,
                        "bou_height":60,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "events":
                [
                    {
                        "evn_uid": "960500897525d8eb8fb84b4013700338",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":87,
                        "bou_y":261,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    },
                    {
                        "evn_uid": "941908090525d8ec7fb8a07093841901",
                        "evn_name":null,
                        "evn_type":"",
                        "evn_marker":"",
                        "evn_is_interrupting":true,
                        "evn_attached_to":null,
                        "evn_cancel_activity":false,
                        "evn_activity_ref":null,
                        "evn_wait_for_completion":false,
                        "evn_error_name":null,
                        "evn_error_code":null,
                        "evn_escalation_name":null,
                        "evn_escalation_code":null,
                        "evn_condition":null,
                        "evn_message":null,
                        "evn_operation_name":null,
                        "evn_operation_implementation_ref":null,
                        "evn_time_date":null,
                        "evn_time_cycle":null,
                        "evn_time_duration":null,
                        "evn_behavior":"",
                        "bou_x":903,
                        "bou_y":303,
                        "bou_width":33,
                        "bou_height":33,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "gateways":
                [
                    {
                        "gat_uid": "403208160525d8ebefb86a0059076243",
                        "gat_name":null,
                        "bou_x":481,
                        "bou_y":306,
                        "bou_width":45,
                        "bou_height":45,
                        "bou_container": "bpmnDiagram",
                        "bou_element_id": "pm_canvas"
                    }
                ],
            "flows":
                [
                    {
                        "flo_uid": "724155752525d8ec9fb8de2003171877",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "960500897525d8eb8fb84b4013700338",
                        "flo_element_origin_type": "bpmnEvent",
                        "flo_element_dest": "278251934525d8ebbfb8565093239226",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":104,"y":261},
                                {"x":104,"y":241},
                                {"x":168,"y":241},
                                {"x":168,"y":309},
                                {"x":233,"y":309}
                            ]
                    },
                    {
                        "flo_uid": "891030650525d8eccfb92c9033321037",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "278251934525d8ebbfb8565093239226",
                        "flo_element_origin_type": "bpmnActivity",
                        "flo_element_dest": "403208160525d8ebefb86a0059076243",
                        "flo_element_dest_type": "bpmnGateway",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":294,"y":278},
                                {"x":294,"y":258},
                                {"x":387,"y":258},
                                {"x":387,"y":329},
                                {"x":481,"y":329}
                            ]
                    },
                    {
                        "flo_uid": "785603906525d8ecffb9879037717215",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest": "326395445525d8ec1fb8768023935580",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":504,"y":306},
                                {"x":504,"y":199},
                                {"x":609,"y":199}
                            ]
                    },
                    {
                        "flo_uid": "531073186525d8ed2fb9d51058983227",
                        "flo_type": "SEQUENCE",
                        "flo_name":null,
                        "flo_element_dest": "588707952525d8ec4fb88c2038077596",
                        "flo_element_origin": "403208160525d8ebefb86a0059076243",
                        "flo_element_origin_type": "bpmnGateway",
                        "flo_element_dest_type": "bpmnActivity",
                        "flo_is_inmediate":true,
                        "flo_condition":null,
                        "flo_state":
                            [
                                {"x":481,"y":329},
                                {"x":461,"y":329},
                                {"x":461,"y":433},
                                {"x":628,"y":433}
                            ]
                    }
                ],
            "artifacts": []
        }
    ]
}
< 201
< Content-Type: application/json
[
    {
        "old_uid": "a5242da840064218638061532405176",
        "new_uid": "146756055527ab40fca1f61040187521",
        "object": "diagram",
    },
    {
        "old_uid":"278251934525d8ebbfb8565093239226", 
        "new_uid": "154619055527bbbbea27110004783861", 
        "object":"activity"
    },
    {
        "old_uid":"326395445525d8ec1fb8768023935580", 
        "new_uid": "44313230351ae0168e63669021546957", 
        "object":"activity"
    },
    {
        "old_uid":"588707952525d8ec4fb88c2038077596", 
        "new_uid": "44313230351ae0168e63669021546957", 
        "object":"activity"
    },
    {
        "old_uid":"960500897525d8eb8fb84b4013700338", 
        "new_uid": "157493645523b4c00067b67020029802",
        "object": "event"
    },
    {
        "old_uid":"941908090525d8ec7fb8a07093841901", 
        "new_uid": "55151892151af5557de5414010032345",
        "object": "event"
    },
    {
        "old_uid":"403208160525d8ebefb86a0059076243", 
        "new_uid": "60108982451ae53bc5786b3013937849",
        "object": "gateway"
    },
    {
        "old_uid":"724155752525d8ec9fb8de2003171877", 
        "new_uid": "87474948551af4835e2cd45025472854",
        "object": "flow"
    },
    {
        "old_uid":"891030650525d8eccfb92c9033321037", 
        "new_uid": "55151892151af5557de5414010032345",
        "object": "flow"
    },
    {
        "old_uid":"785603906525d8ecffb9879037717215", 
        "new_uid": "88931079151af479d543650091554690",
        "object": "flow"
    },
    {
        "old_uid":"531073186525d8ed2fb9d51058983227", 
        "new_uid": "9357304135242e2c7da7a59001869953",
        "object": "flow"
    }
]


Delete a `project`
DELETE /project/{prj_uid}
< 200


--
Project Activity Resources
--

Get ***properties & definition*** of a project `activity` 
GET /project/{prj_uid}/activity/{act_uid}
< 200
{
    "definition": {},
    "properties": 
    {
        "tas_priority_variable": "@@SYS_SYS",
        "tas_derivation_screen_tpl": "MyTemplate.html"
        "tas_assign_type": "SELF_SERVICE_EVALUATE",
        "tas_assign_variable": "@@SYS_NEXT_USER_TO_BE_ASSIGNED",
        "tas_group_variable": "@@SYS_GROUP_TO_BE_ASSIGNED",
        "tas_selfservice_timeout": 0,
        "tas_selfservice_time": "1",
        "tas_selfservice_time_unit": "HOURS",
        "tas_selfservice_trigger_uid": "00000000000000000000000000000001"
        "tas_transfer_fly": "FALSE",
        "tas_duration": "1",
        "tas_timeunit": "HOURS",
        "tas_type_day": "2",
        "tas_calendar": ""
        "tas_type": "ADHOC"
        "tas_def_title": "Sample Title",
        "tas_def_description": "Sample Description"
        "send_email": "TRUE",
        "tas_def_subject_message": "Sample Subject",
        "tas_def_message_type": "text",
        "tas_def_message": "Sample Message",
        "tas_def_message_template": "MyTemplate.html"
    }
}

Get ***definition*** of a project activity
GET /project/{prj_uid}/activity/{act_uid}?filter=definition
< 200
{
    "definition": {}
}

Get ***properties*** of a project activity 
GET /project/{prj_uid}/activity/{act_uid}?filter=properties
< 200
{
    "properties":
    {
        "tas_priority_variable": "@@SYS_SYS",
        "tas_derivation_screen_tpl": "MyTemplate.html"
        "tas_assign_type": "SELF_SERVICE_EVALUATE",
        "tas_assign_variable": "@@SYS_NEXT_USER_TO_BE_ASSIGNED",
        "tas_group_variable": "@@SYS_GROUP_TO_BE_ASSIGNED",
        "tas_selfservice_timeout": 0,
        "tas_selfservice_time": "1",
        "tas_selfservice_time_unit": "HOURS",
        "tas_selfservice_trigger_uid": "00000000000000000000000000000001"
        "tas_transfer_fly": "FALSE",
        "tas_duration": "1",
        "tas_timeunit": "HOURS",
        "tas_type_day": "2",
        "tas_calendar": ""
        "tas_type": "ADHOC"
        "tas_def_title": "Sample Title",
        "tas_def_description": "Sample Description"
        "send_email": "TRUE",
        "tas_def_subject_message": "Sample Subject",
        "tas_def_message_type": "text",
        "tas_def_message": "Sample Message",
        "tas_def_message_template": "MyTemplate.html"
    }
}

Update a project activity
PUT /project/{prj_uid}/activity/{act_uid}
> Content-Type: application/json
{
    "definition": {},
    "properties": 
    {
        "tas_priority_variable": "@@SYS_SYS",
        "tas_derivation_screen_tpl": "MyTemplate.html"
        "tas_assign_type": "SELF_SERVICE_EVALUATE",
        "tas_assign_variable": "@@SYS_NEXT_USER_TO_BE_ASSIGNED",
        "tas_group_variable": "@@SYS_GROUP_TO_BE_ASSIGNED",
        "tas_selfservice_timeout": 0,
        "tas_selfservice_time": "1",
        "tas_selfservice_time_unit": "HOURS",
        "tas_selfservice_trigger_uid": "00000000000000000000000000000001"
        "tas_transfer_fly": "FALSE",
        "tas_duration": "1",
        "tas_timeunit": "HOURS",
        "tas_type_day": "2",
        "tas_calendar": ""
        "tas_type": "ADHOC"
        "tas_def_title": "Sample Title",
        "tas_def_description": "Sample Description"
        "send_email": "TRUE",
        "tas_def_subject_message": "Sample Subject",
        "tas_def_message_type": "text",
        "tas_def_message": "Sample Message",
        "tas_def_message_template": "MyTemplate.html"
    }
}
< 200


Delete a project activity

**This is used to delete an activity and its relations from a diagram.**
DELETE /project/{prj_uid}/activity/{act_uid}
< 200


--
Project Properties - Assignee Resources
--

List assignees of an `activity`

###Optional Parameters
name          | type    | Description 
:------------ | :------ | :-----------
start         | integer | To specify a start index.
limit         | integer | To delimit the numbers of records to return.
filter        | string  | To specify a search term to filter the list, the search term will be matched with all assignee fields.

GET /project/{prj_uid}/activity/{act_uid}/assignee?filter=john&start=0&limit=50
< 200 
< Content-Type: application/json
[
    {
        "aas_uid": "4e2745a3fdbd977d1339862ae390ad13",
        "aas_name": "Mark",
        "aas_lastname": "Smith",
        "aas_username": "mark",
        "aas_type": "user"
    },
    {
        "aas_uid": "60108982451ae53bc5786b3013937849",
        "aas_name": "John",
        "aas_lastname": "Doe",
        "aas_username": "jdoe",
        "aas_type": "user"
    },
    {
        "aas_uid": "157493645523b4c00067b67020029802",
        "aas_name": "Administrators",
        "aas_lastname": "",
        "aas_username": "",
        "aas_type": "group"
    }
]

Get a list of available users and groups to be assigned to an `activity`
 
###Optional Parameters
name          | type    | Description 
:------------ | :------ | :-----------
start         | integer | To specify a start index.
limit         | integer | To delimit the numbers of records to return.
filter        | string  | To specify a search term to filter the list, the search term will be matched with all assignee fields.
GET /project/{prj_uid}/activity/{act_uid}/available-assignee?filter=john&start=0&limit=50
< 200 
< Content-Type: application/json
[
    {
        "aas_uid": "8f30daa78a440ab308727ca33381a545",
        "aas_name": "James",
        "aas_lastname": "Johnson",
        "aas_username": "james",
        "aas_type": "user"
    },
    {
        "aas_uid": "ae1e2034be750da53e48582cddc2ebc7",
        "aas_name": "Robert",
        "aas_lastname": "Williams",
        "aas_username": "robert",
        "aas_type": "user"
    },
    {
        "aas_uid": "184131195492c7a04cba5f9056989964",
        "aas_name": "Mary",
        "aas_lastname": "Rose",
        "aas_username": "mary",
        "aas_type": "user"
    },
    {
        "aas_uid": "1846526764c8905435c74e2028286704",
        "aas_name": "Employees",
        "aas_lastname": "",
        "aas_username": "",
        "aas_type": "group"
    }
    {
        "aas_uid": "1846526764c8905435c74e2028286704",
        "aas_name": "Plant Managers",
        "aas_lastname": "",
        "aas_username": "",
        "aas_type": "group"
    }
]

Get a single user or group of an `activity`
GET /project/{prj_uid}/activity/{act_uid}/assignee/{aas_uid}
< 200
< Content-Type: application/json
{
    "aas_uid": "4e2745a3fdbd977d1339862ae390ad13",
    "aas_name": "Mark",
    "aas_lastname": "Smith",
    "aas_username": "mark",
    "aas_type": "user"
}

Asign a user or group to an `activity`
POST /project/{prj_uid}/activity/{act_uid}/assignee
> Content-Type: application/json
{
    "aas_uid": "977d1339862ae390ad134e2745a3fdbd",
    "aas_type": "user"
}
< 201


Remove a assignee of an `activity`
DELETE /project/{prj_uid}/activity/{act_uid}/assignee/{aas_uid}
> Content-Type: application/json
< 200

--
Project Properties - Ad hoc Assignee Resources
--

List Ad hoc assignees of an `activity`

###Optional Parameters
name          | type    | Description 
:------------ | :------ | :-----------
start         | integer | To specify a start index.
limit         | integer | To delimit the numbers of records to return.
filter        | string  | To specify a search term to filter the list, the search term will be matched with all assignee fields.

GET /project/{prj_uid}/activity/{act_uid}/adhoc-assignee?filter=john&start=0&limit=50
< 200 
< Content-Type: application/json
[
    {
        "ada_uid": "4e2745a3fdbd977d1339862ae390ad13",
        "ada_name": "Mark",
        "ada_lastname": "Smith",
        "ada_username": "mark",
        "ada_type": "user"
    },
    {
        "ada_uid": "60108982451ae53bc5786b3013937849",
        "ada_name": "John",
        "ada_lastname": "Doe",
        "ada_username": "jdoe",
        "ada_type": "user"
    },
    {
        "ada_uid": "157493645523b4c00067b67020029802",
        "ada_name": "Administrators",
        "ada_lastname": "",
        "ada_username": "",
        "ada_type": "group"
    }
]

Get a list of available Ad hoc users and groups to be assigned to an `activity`
 
###Optional Parameters
name          | type    | Description 
:------------ | :------ | :-----------
start         | integer | To specify a start index.
limit         | integer | To delimit the numbers of records to return.
filter        | string  | To specify a search term to filter the list, the search term will be matched with all assignee fields.
GET /project/{prj_uid}/activity/{act_uid}/adhoc-available-assignee?filter=john&start=0&limit=50
< 200 
< Content-Type: application/json
[
    {
        "ada_uid": "8f30daa78a440ab308727ca33381a545",
        "ada_name": "James",
        "ada_lastname": "Johnson",
        "ada_username": "james",
        "ada_type": "user"
    },
    {
        "ada_uid": "ae1e2034be750da53e48582cddc2ebc7",
        "ada_name": "Robert",
        "ada_lastname": "Williams",
        "ada_username": "robert",
        "ada_type": "user"
    },
    {
        "ada_uid": "184131195492c7a04cba5f9056989964",
        "ada_name": "Mary",
        "ada_lastname": "Rose",
        "ada_username": "mary",
        "ada_type": "user"
    },
    {
        "ada_uid": "1846526764c8905435c74e2028286704",
        "ada_name": "Employees",
        "ada_lastname": "",
        "ada_username": "",
        "ada_type": "group"
    }
    {
        "ada_uid": "1846526764c8905435c74e2028286704",
        "ada_name": "Plant Managers",
        "ada_lastname": "",
        "ada_username": "",
        "ada_type": "group"
    }
]

Get a single Ad hoc user or group of an `activity`
GET /project/{prj_uid}/activity/{act_uid}/assignee/{ada_uid}
< 200
< Content-Type: application/json
{
    "ada_uid": "4e2745a3fdbd977d1339862ae390ad13",
    "ada_name": "Mark",
    "ada_lastname": "Smith",
    "ada_username": "mark",
    "ada_type": "user"
}

Asign a Ad hoc user or group to an `activity`
POST /project/{prj_uid}/activity/{act_uid}/adhoc-assignee
> Content-Type: application/json
{
    "ada_uid": "977d1339862ae390ad134e2745a3fdbd",
    "ada_type": "user"
}
< 201


Remove a Ad hoc assignee of an `activity`
DELETE /project/{prj_uid}/activity/{act_uid}/adhoc-assignee/{ada_uid}
> Content-Type: application/json
< 200


--
Project Properties - Step Resources
--

List assigned `steps` to an Activity
GET /project/{prj_uid}/activity/{act_uid}/steps
< 200 
< Content-Type: application/json
[
    {
        "step_uid": "25bd5127e1bfae143843382b12207b03",
        "step_type_obj": "DYNAFORM",
        "step_uid_obj": "e143843382b12207b0325bd5127e1bfa",
        "step_condition": "",
        "step_position": "",
        "step_mode": "EDIT",
        "obj_title": "dyn_1",
        "obj_description": "Dynaform #1"
    },
    {
        "step_uid": "382b12207b0325bd5127e1bfae143843",
        "step_type_obj": "DYNAFORM",
        "step_uid_obj": "ac632c411a07bd64721ca7764311d437",
        "step_condition": "",
        "step_position": "",
        "step_mode": "EDIT",
        "obj_title": "dyn_2",
        "obj_description": "Dynaform #2"
    }
]

List available `steps` to assign to an Activity
GET /project/{prj_uid}/activity/{act_uid}/available-steps
< 200 
< Content-Type: application/json
[
    {
        "obj_uid": "051ec4c12ca5205436a337cf83f29881",
        "obj_title": "dyn_3",
        "obj_description": "Dynaform #3",
        "obj_type": "DYNAFORM"
    },
    {
        "obj_uid": "833d579daf212fd4849b00b26063bf04",
        "obj_title": "dyn_4",
        "obj_description": "Dynaform #4",
        "obj_type": "DYNAFORM"
    },
    {
        "obj_uid": "942fdcef9fdca48fbf88e3733cf66cea",
        "obj_title": "outputdoc_1",
        "obj_description": "Input Docucument #1",
        "obj_type": "INPUT_DOCUMENT"
    }
]

Get a single `step` assigned to an Activity
GET /project/{prj_uid}/activity/{act_uid}/step/{step_uid}
< 200
< Content-Type: application/json
{
    "step_uid": "25bd5127e1bfae143843382b12207b03",
    "step_type_obj": "DYNAFORM",
    "step_uid_obj": "e143843382b12207b0325bd5127e1bfa",
    "step_condition": "",
    "step_position": "",
    "step_mode": "EDIT",
    "obj_title": "dyn_1",
    "obj_description": "Dynaform #1"
}

Assing a `step` to a Activity
POST /project/{prj_uid}/activity/{act_uid}/step
> Content-Type: application/json
{
    "step_uid": "25bd5127e1bfae143843382b12207b03",
    "step_type_obj": "DYNAFORM",
    "step_uid_obj": "e143843382b12207b0325bd5127e1bfa",
    "step_condition": "",
    "step_position": "",
    "step_mode": "EDIT"
}
< 200
< Content-Type: application/json
{
    "old_uid":"25bd5127e1bfae143843382b12207b03", 
    "new_uid": "82b12207b0325bd5127e1bfae1438433"
}

Update a `step` assignation of an Activity
PUT /project/{prj_uid}/activity/{act_uid}/step/{step_uid}
> Content-Type: application/json
{
    "step_type_obj": "DYNAFORM",
    "step_uid_obj": "e143843382b12207b0325bd5127e1bfa",
    "step_condition": "@@var1 == 1",
    "step_position": "2",
    "step_mode": "VIEW"
}
< 200


Unassign a `step` from an activity
DELETE /project/{prj_uid}/activity/{act_uid}/step/{step_uid}
< 200


List assigned `triggers` to a Step 
GET /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/triggers
< 200 
< Content-Type: application/json
[
    {
        "step_uid": "38768199848d680986fed11033234711",
        "tri_uid": "11249313348d67d3d7862a3048595231",
        "st_type": "AFTER",
        "st_condition": "",
        "st_position": "1"
    },
    {
        "step_uid": "38768199848d680986fed11033234711",
        "tri_uid": "3399325724ac11634a29294071887017",
        "st_type": "BEFORE",
        "st_condition": "@@sheetApproved == '1'",
        "st_position": "1"
    }
]

List available `triggers` to assign to a Step
GET /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/available-triggers
< 200 
< Content-Type: application/json
[
    {
        "tri_uid": "3399325724ac11634a29294071887017",
        "tri_type": "SCRIPT",
        "tri_webbot": "
$outputID=\"6873869084ac115856a8325014651845\";
PMFGenerateOutputDocument($outputID);",
        "tri_param": ""
    },
    {
        "tri_uid": "8488283114bffe914417cb5020528882",
        "tri_type": "SCRIPT",
        "tri_webbot": "@@average = (@@n1 + @@n2 + @@n3) / 3;",
        "tri_param": ""
    }
]

Get a single `trigger` assigned to a Step
GET /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/trigger/{tri_uid}
< 200 
< Content-Type: application/json
{
    "tri_uid": "8488283114bffe914417cb5020528882",
    "tri_type": "SCRIPT",
    "tri_webbot": "@@average = (@@n1 + @@n2 + @@n3) / 3;",
    "tri_param": ""
}

Assign a `trigger` to a Step

###Required Parameters
name        | type   | Description
:---------- | :----- | :------------
tri_uid     | string | The trigger UID

###Optional Parameters
name             | type   | Description 
:--------------- | :----- | :-----------
st_type          | string | execution time, accepted values: **AFTER**, **BEFORE**.
st_condition     | string | Trigger Condition, the trigger only will be executed if it is evaluated `true`.
st_position      | integer| Position that especifies the trigger order execution, it starts in **1**.

POST /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/trigger
> Content-Type: application/json
{
    "tri_uid": "11249313348d67d3d7862a3048595231",
    "st_type": "AFTER",
    "st_condition": "@@APPROVED == 'Y'",
    "st_position": "2"
}
< 201 


Update a `trigger` assignation of a Step
PUT /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/trigger/{tri_uid}
> Content-Type: application/json
{
    "st_type": "BEFORE",
    "st_condition": "@@APPROVED == 'N'",
    "st_position": "1"
}
< 200 


Remove a `trigger` assignation of a Step
DELETE /project/{prj_uid}/activity/{act_uid}/step/{step_uid}/trigger/{tri_uid}
< 200 

