<?php
global $RBAC;

if ($RBAC->userCanAccess("PM_SETUP") != 1) {
    G::SendTemporalMessage("ID_USER_HAVENT_RIGHTS_PAGE", "error", "labels");
    exit(0);
}

$c = new Configurations();
$configPage = $c->getConfiguration( "auditLogList", "pageSize", null, $_SESSION["USER_LOGGED"] );

$config = array ();
$config["pageSize"] = (isset( $configPage["pageSize"] )) ? $configPage["pageSize"] : 20;

$arrayAction = array (array ("ALL", G::LoadTranslation( "ID_ALL" )),
            array ("CreateUser", G::LoadTranslation( "ID_CREATE_USER" )),
            array ("UpdateUser", G::LoadTranslation( "ID_UPDATE_USER" )),
            array ("DeleteUser", G::LoadTranslation( "ID_DELETE_USER" )),
            array ("EnableUser", G::LoadTranslation( "ID_ENABLE_USER" )),
            array ("DisableUser", G::LoadTranslation( "ID_DISABLE_USER" )),
            array ("AssignAuthenticationSource", G::LoadTranslation( "ID_ASSIGN_AUTHENTICATION_SOURCE" )),
            array ("AssignUserToGroup", G::LoadTranslation( "ID_ASSIGN_USER_TO_GROUP" )),
            array ("CreateAuthSource", G::LoadTranslation( "ID_CREATE_AUTH_SOURCE" )),
            array ("UpdateAuthSource", G::LoadTranslation( "ID_UPDATE_AUTH_SOURCE" )),
            array ("DeleteAuthSource", G::LoadTranslation( "ID_DELETE_AUTH_SOURCE" )),
            array ("CreateRole", G::LoadTranslation( "ID_CREATE_ROLE" )),
            array ("UpdateRole", G::LoadTranslation( "ID_UPDATE_ROLE" )),
            array ("DeleteRole", G::LoadTranslation( "ID_DELETE_ROLE" )),
            array ("AssignUserToRole", G::LoadTranslation( "ID_ASSIGN_USER_TO_ROLE" )),
            array ("DeleteUserToRole", G::LoadTranslation( "ID_DELETE_USER_TO_ROLE" )),
            array ("AddPermissionToRole", G::LoadTranslation( "ID_ADD_PERMISSION_TO_ROLE" )),
            array ("DeletePermissionToRole", G::LoadTranslation( "ID_DELETE_PERMISSION_TO_ROLE" )),
            array ("CreateSkin", G::LoadTranslation( "ID_CREATE_SKIN" )),
            array ("ImportSkin", G::LoadTranslation( "ID_IMPORT_SKIN" )),
            array ("ExportSkin", G::LoadTranslation( "ID_EXPORT_SKIN" )),
            array ("DeleteSkin", G::LoadTranslation( "ID_DELETE_SKIN" )),					  
            array ("CreateGroup", G::LoadTranslation( "ID_CREATE_GROUP" )),
            array ("UpdateGroup", G::LoadTranslation( "ID_UPDATE_GROUP" )),
            array ("DeleteGroup", G::LoadTranslation( "ID_DELETE_GROUP" )),					  
            array ("CreateCategory", G::LoadTranslation( "ID_CREATE_CATEGORY" )),
            array ("UpdateCategory", G::LoadTranslation( "ID_UPDATE_CATEGORY" )),
            array ("DeleteCategory", G::LoadTranslation( "ID_DELETE_CATEGORY" )),
            array ("BuildCache", G::LoadTranslation( "ID_BUILD_CACHE" )),
            array ("ClearCache", G::LoadTranslation( "ID_CLEAR_CACHE" )),
            array ("ClearCron", G::LoadTranslation( "ID_CLEAR_CRON" )),
            array ("UpdateEnvironmentSettings", G::LoadTranslation( "ID_UPDATE_ENVIRONMENT_SETTINGS" )),
            array ("UpdateLoginSettings", G::LoadTranslation( "ID_UPDATE_LOGIN_SETTINGS" )),
            array ("EnableHeartBeat", G::LoadTranslation( "ID_ENABLE_HEART_BEAT" )),
            array ("DisableHeartBeat", G::LoadTranslation( "ID_DISABLE_HEART_BEAT" )),
            array ("CreatePmtable", G::LoadTranslation( "ID_CREATE_PMTABLE" )),
            array ("UpdatePmtable", G::LoadTranslation( "ID_UPDATE_PMTABLE" )),
            array ("DeletePmtable", G::LoadTranslation( "ID_DELETE_PMTABLE" )),
            array ("AddDataPmtable", G::LoadTranslation( "ID_ADD_DATA_PMTABLE" )),
            array ("UpdateDataPmtable", G::LoadTranslation( "ID_UPDATE_DATA_PMTABLE" )),
            array ("DeleteDataPmtable", G::LoadTranslation( "ID_DELETE_DATA_PMTABLE" )),
            array ("ImportTable", G::LoadTranslation( "ID_IMPORT_TABLE" )),
            array ("ExportTable", G::LoadTranslation( "ID_EXPORT_TABLE" )),
            array ("CreateCalendar", G::LoadTranslation( "ID_CREATE_CALENDAR" )),
            array ("UpdateCalendar", G::LoadTranslation( "ID_UPDATE_CALENDAR" )),
            array ("DeleteCalendar", G::LoadTranslation( "ID_DELETE_CALENDAR" )),
            array ("CreateDashletInstance", G::LoadTranslation( "ID_CREATE_DASHLET_INSTANCE" )),
            array ("UpdateDashletInstance", G::LoadTranslation( "ID_UPDATE_DASHLET_INSTANCE" )),
            array ("DeleteDashletInstance", G::LoadTranslation( "ID_DELETE_DASHLET_INSTANCE" )),
            array ("CreateDepartament", G::LoadTranslation( "ID_CREATE_DEPARTAMENT" )),
            array ("CreateSubDepartament", G::LoadTranslation( "ID_CREATE_SUB_DEPARTAMENT" )),
            array ("UpdateDepartament", G::LoadTranslation( "ID_UPDATE_DEPARTAMENT" )),
            array ("UpdateSubDepartament", G::LoadTranslation( "ID_UPDATE_SUB_DEPARTAMENT" )),
            array ("DeleteDepartament", G::LoadTranslation( "ID_DELETE_DEPARTAMENT" )),
            array ("AssignManagerToDepartament", G::LoadTranslation( "ID_ASSIGN_MANAGER_TO_DEPARTAMENT" )),
            array ("AssignUserToDepartament", G::LoadTranslation( "ID_ASSIGN_USER_TO_DEPARTAMENT" )),
            array ("RemoveUsersFromDepartament", G::LoadTranslation( "ID_REMOVE_USERS_FROM_DEPARTAMENT" )),
            array ("AssignUserToGroup", G::LoadTranslation( "ID_ASSIGN_USER_TO_GROUP" )),
            array ("UploadLanguage", G::LoadTranslation( "ID_UPLOAD_LANGUAGE" )),
            array ("ExportLanguage", G::LoadTranslation( "ID_EXPORT_LANGUAGE" )),
            array ("DeleteLanguage", G::LoadTranslation( "ID_DELETE_LAGUAGE" )),
            array ("UploadSystemSettings", G::LoadTranslation( "ID_UPLOAD_SYSTEM_SETTINGS" )),
            array ("UpdateEmailSettings", G::LoadTranslation( "ID_UPDATE_EMAIL_SETTINGS" )),
            array ("CreateEmailSettings", G::LoadTranslation( "ID_CREATE_EMAIL_SETTINGS" )),
            array ("UploadLogo", G::LoadTranslation( "ID_UPLOAD_LOGO" )),
            array ("DeleteLogo", G::LoadTranslation( "ID_DELETE_LOGO" )),
            array ("RestoreLogo", G::LoadTranslation( "ID_RESTORE_LOGO" )),
            array ("ReplaceLogo", G::LoadTranslation( "ID_REPLACE_LOGO" )),
            array ("InstallPlugin", G::LoadTranslation( "ID_INSTALL_PLUGIN" )),
            array ("EnablePlugin", G::LoadTranslation( "ID_ENABLE_PLUGIN" )),
            array ("DisablePlugin", G::LoadTranslation( "ID_DISABLE_PLUGIN" )),
            array ("RemovePlugin", G::LoadTranslation( "ID_REMOVE_PLUGIN" )),
            array ("SetColumns", G::LoadTranslation( "ID_SET_COLUMNS" )),
            array ("EnableAuditLog", G::LoadTranslation( "ID_ENABLE_AUDIT_LOG" )),
            array ("DisableAuditLog", G::LoadTranslation( "ID_DISABLE_AUDIT_LOG" )),
            array ("EditProcess", G::LoadTranslation( "ID_EDIT_PROCESS" )),
            array ("ExportProcess", G::LoadTranslation( "ID_EXPORT_PROCESS" )),
            array ("WebEntry", G::LoadTranslation( "ID_WEB_ENTRY" )),
            array ("AssignRole", G::LoadTranslation( "ID_ASSIGN_ROLE" )),
            array ("RemoveUser", G::LoadTranslation( "ID_REMOVE_USER" )),
            array ("AddTask", G::LoadTranslation( "ID_ADD_TASK" )),
            array ("AddSubProcess", G::LoadTranslation( "ID_ADD_SUB_PROCESS" )),
            array ("SaveTaskPosition", G::LoadTranslation( "ID_SAVE_TASK_POSITION" )),
            array ("AddHorizontalLine", G::LoadTranslation( "ID_ADD_HORIZONTAL_LINE" )),
            array ("AddVerticalLine", G::LoadTranslation( "ID_ADD_VERTICAL_LINE" )),
            array ("SaveGuidePosition", G::LoadTranslation( "ID_SAVE_GUIDE_POSITION" )),
            array ("DeleteLine", G::LoadTranslation( "ID_DELETE_LINE" )),
            array ("DeleteLines", G::LoadTranslation( "ID_DELETE_LINES" )),
            array ("AddText", G::LoadTranslation( "ID_ADD_TEXT" )),
            array ("UpdateText", G::LoadTranslation( "ID_UPDATE_TEXT" )),
            array ("SaveTextPosition", G::LoadTranslation( "ID_SAVE_TEXT_POSITION" )),
            array ("DeleteText", G::LoadTranslation( "ID_DELETE_TEXT" )),
            array ("ProcessFileManager", G::LoadTranslation( "ID_PROCESS_FILE_MANAGER" )),
            array ("ProcessPermissions", G::LoadTranslation( "ID_PROCESS_PERMISSIONS" )),
            array ("DeletePermissions", G::LoadTranslation( "ID_DELETE_PERMISSIONS" )),
            array ("AssignSupervisorDynaform", G::LoadTranslation( "ID_ASSIGN_SUPERVISOR_DYNAFORM" )),
            array ("RemoveSupervisorDynaform", G::LoadTranslation( "ID_REMOVE_SUPERVISOR_DYNAFORM" )),
            array ("AssignSupervisorInput", G::LoadTranslation( "ID_ASSIGN_SUPERVISOR_INPUT" )),
            array ("RemoveSupervisorInput", G::LoadTranslation( "ID_REMOVE_SUPERVISOR_INPUT" )),
            array ("CaseTrackers", G::LoadTranslation( "ID_CASE_TRACKERS" )),
            array ("Events", G::LoadTranslation( "ID_EDIT_PROCESS" )),
            array ("CreateDynaform", G::LoadTranslation( "ID_CREATE_DYNAFORM" )),
            array ("UpdateDynaform", G::LoadTranslation( "ID_UPDATE_DYNAFORM" )),
            array ("DeleteDynaform", G::LoadTranslation( "ID_DELETE_DYNAFORM" )),
            array ("ConditionsEditorDynaform", G::LoadTranslation( "ID_CONDITIONS_EDITOR_DYNAFORM" )),
            array ("CreateCaseScheduler", G::LoadTranslation( "ID_CREATE_CASE_SCHEDULER" )),
            array ("UpdateCaseScheduler", G::LoadTranslation( "ID_UPDATE_CASE_SCHEDULER" )),
            array ("DeleteCaseScheduler", G::LoadTranslation( "ID_DELETE_CASE_SCHEDULER" )),
            array ("CreateDatabaseConnection", G::LoadTranslation( "ID_CREATE_DATABASE_CONNECTION" )),
            array ("UpdateDatabaseConnection", G::LoadTranslation( "ID_UPDATE_DATABASE_CONNECTION" )),
            array ("DeleteDatabaseConnection", G::LoadTranslation( "ID_DELETE_DATABASE_CONNECTION" )),
            array ("CreateInputDocument", G::LoadTranslation( "ID_CREATE_INPUT_DOCUMENT" )),
            array ("UpdateInputDocument", G::LoadTranslation( "ID_UPDATE_INPUT_DOCUMENT" )),
            array ("DeleteInputDocument", G::LoadTranslation( "ID_DELETE_INPUT_DOCUMENT" )),
            array ("CreateOutputDocument", G::LoadTranslation( "ID_CREATE_OUTPUT_DOCUMENT" )),
            array ("UpdateOutputDocument", G::LoadTranslation( "ID_UPDATE_OUTPUT_DOCUMENT" )),
            array ("DeleteOutputDocument", G::LoadTranslation( "ID_DELETE_OUTPUT_DOCUMENT" )),
            array ("CreateTrigger", G::LoadTranslation( "ID_CREATE_TRIGGER" )),
            array ("UpdateTrigger", G::LoadTranslation( "ID_UPDATE_TRIGGER" )),
            array ("DeleteTrigger", G::LoadTranslation( "ID_DELETE_TRIGGER" )),
            array ("DerivationRule", G::LoadTranslation( "ID_DERIVATION_RULE" )),
            array ("DeleteTask", G::LoadTranslation( "ID_DELETE_TASK" )),
            array ("DeleteSubProcess", G::LoadTranslation( "ID_DELETE_SUB_PROCESS" )),
            array ("OptionsMenuTask", G::LoadTranslation( "ID_OPTIONS_MENU_TASK" )),
            array ("SaveTaskProperties", G::LoadTranslation( "ID_SAVE_TASK_PROPERTIES" )),
            array ("DeleteRoutes", G::LoadTranslation( "ID_DELETE_ROUTES" )),
            array ("NewConditionFromStep", G::LoadTranslation( "ID_NEW_CONDITION_FROM_STEP" )),
            array ("AssignTrigger", G::LoadTranslation( "ID_ASSIGN_TRIGGER" )),
            array ("UpTrigger", G::LoadTranslation( "ID_UP_TRIGGER" )),
            array ("DownTrigger", G::LoadTranslation( "ID_DOWN_TRIGGER" )),
            array ("StepDelete", G::LoadTranslation( "ID_STEP_DELETE" )), 
            array ("StepUp", G::LoadTranslation( "ID_STEP_UP" )), 
            array ("StepDown", G::LoadTranslation( "ID_STEP_DOWN" )), 
            array ("SaveNewStep", G::LoadTranslation( "ID_SAVE_NEW_STEP" )),
            array ("AssignUserTask", G::LoadTranslation( "ID_ASSIGN_USER_TASK" )), 
            array ("AssignGroupTask", G::LoadTranslation( "ID_ASSIGN_GROUP_TASK" )),
            array ("DeleteUserTask", G::LoadTranslation( "ID_DELETE_USER_TASK" )),
            array ("DeleteGroupTask", G::LoadTranslation( "ID_DELETE_GROUP_TASK" ))                
        );

$oHeadPublisher = &headPublisher::getSingleton();
$oHeadPublisher->addExtJsScript( "setup/auditLog", true );
$oHeadPublisher->assign( "CONFIG", $config );
$oHeadPublisher->assign( "ACTION", $arrayAction );
G::RenderPage( "publish", "extJs" );
