version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   resource_class: large
   branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
   steps:         
     - checkout
     - run: ls -la /tmp/
     - run: service mysqld restart
     - run: mysql -u root -ppassword -e "create database test;"    
     - run: composer install
     - run:
        name: Run Test Units
        command: |
          set -e
          find tests/ -name "*Test.php" > tests.list
          input="tests.list"
          while IFS= read -r line
          do
            if [ $line != "tests/unit/workflow/engine/src/ProcessMaker/BusinessModel/SkinsTest.php" ] && [ $line != "tests/unit/workflow/engine/src/ProcessMaker/BusinessModel/LanguageTest.php" ];
            then
              vendor/phpunit/phpunit/phpunit --coverage-html ./coverage  $line
            fi            
          done < "$input" 
     - run: ls -la coverage
     - run: mysql -u root -ppassword -e "use test; show tables;"
     - store_artifacts:
          path: coverage
          destination: coverage
        