version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   resource_class: large
   branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
   steps:         
     - checkout
     - run: ls -la /tmp/
     - run: service mysqld restart
     - run: mysql -u root -ppassword -e "create database test;"    
     - run: composer install
     - run: vendor/phpunit/phpunit/phpunit --coverage-html ./coverage  tests/unit/workflow/engine/src/ProcessMaker/Model/DelegationTest.php
     - run: ls -la coverage
     - run: mysql -u root -ppassword -e "use test; show tables;"
     - store_artifacts:
          path: coverage
          destination: coverage
        