version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   resource_class: large
   branches:
     only:
       # Only executed circleci for this branch
       - develop
   steps:         
     - checkout
     - run: service mysqld restart
     - run: mysql -u root -ppassword -e "create database test;"    
     - run: composer install
     - run:
        name: Run Test Units
        command: |
          set -e                  
          mkdir coverage
          vendor/phpunit/phpunit/phpunit --testdox-html coverage/result.html --coverage-html coverage  tests/unit/     
     - store_artifacts:
          path: coverage
          destination: coverage
        