version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   resource_class: large
   branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
   steps:         
     - checkout
     - run: ls -la /tmp/
     - run: service mysqld restart
     - run: mysql -u root -ppassword -e "create database test;"    
     - run: composer install
     - run:
        name: Run Test Units
        command: |
          find tests/unit/ -type f -name "*.php" > tests.list
          input="tests.list"
          while IFS= read -r line
          do
            vendor/phpunit/phpunit/phpunit --coverage-html ./coverage  $line
          done < "$input" 
     - run: ls -la coverage
     - run: mysql -u root -ppassword -e "use test; show tables;"
     - store_artifacts:
          path: coverage
          destination: coverage
        