version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
   steps:    
     - run: ls -la /etc/init.d/
     - run: service mysqld restart
     - run: service mysqld status
     - checkout
     - run: mysql -u root -ppassword -e "create database test;"
     - run: vendor/phpunit/phpunit/phpunit --coverage-html ./coverage  tests/unit/workflow/engine/src/ProcessMaker/Model/DelegationTest.php
     - run: ls -la coverage
        