version: 2
jobs:
 build:
   working_directory: ~/processmaker
   docker:
     - image: devopsstacks/pm:n225-phpunit
   branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
   steps:
     #- run: yum install -y git
     - run: yum install -y git     
     - checkout
     - run: 
        name: swich folder
        command: |
            cd /processmaker
            pwd