version: 2
jobs:
  build:
    docker:
      - image: devopsstacks/pm:n225-phpunit
    working_directory: ~/processmaker
    branches:
     only:
       # Only executed circleci for this branch
       - /KR.*/
    steps:
      # - run: yum -y install ssh
      - run: yum install -y git
      - checkout:
      - run: 
          name: swich folder
          command: |
             cd /processmaker
             pwd
     