@ProcessMakerMichelangelo @RestAPI
Feature: Output Documents Negative Tests

  Scenario Outline: Create a new output document for a project
    Given POST this data:
      """
      {
        "out_doc_title":            "<out_doc_title>",
        "out_doc_description":      "<out_doc_description>",
        "out_doc_filename":         "<out_doc_filename>",
        "out_doc_template":         "<out_doc_template>",
        "out_doc_report_generator": "<out_doc_report_generator>",
        "out_doc_landscape":        "<out_doc_landscape>",
        "out_doc_media":            "<out_doc_media>",
        "out_doc_left_margin":      "<out_doc_left_margin>",
        "out_doc_right_margin":     "<out_doc_right_margin>",
        "out_doc_top_margin":       "<out_doc_top_margin>",
        "out_doc_bottom_margin":    "<out_doc_bottom_margin>",
        "out_doc_generate":         "<out_doc_generate>",
        "out_doc_type":             "<out_doc_type>",
        "out_doc_current_revision": "<out_doc_current_revision>",
        "out_doc_field_mapping":    "<out_doc_field_mapping>",
        "out_doc_versioning":       "<out_doc_versioning>",
        "out_doc_destination_path": "<out_doc_destination_path>",
        "out_doc_tags":             "<out_doc_tags>",
        "out_doc_pdf_security_enabled":        "<out_doc_pdf_security_enabled>",
        "out_doc_pdf_security_open_password":  "<out_doc_pdf_security_open_password>",
        "out_doc_pdf_security_owner_password": "<out_doc_pdf_security_owner_password>",
        "out_doc_pdf_security_permissions":    "<out_doc_pdf_security_permissions>"
      }
      """
      And I request "project/<project>/output-document"
      Then the response status code should be 400


      Examples:

        | project                          | out_doc_title                     | out_doc_description                      |out_doc_filename  | out_doc_template | out_doc_report_generator | out_doc_landscape | out_doc_media | out_doc_left_margin | out_doc_right_margin | out_doc_top_margin | out_doc_bottom_margin | out_doc_generate | out_doc_type | out_doc_current_revision | out_doc_field_mapping | out_doc_versioning | out_doc_destination_path | out_doc_tags | out_doc_pdf_security_enabled | out_doc_pdf_security_open_password | out_doc_pdf_security_owner_password | out_doc_pdf_security_permissions |
        | 4224292655297723eb98691001100052 | Endpoint New Version 4            | Output Document new version - EndPoint   | Output 5         |                  | @#$%¼¤¾½                 | 1                 | Letter        | 30                  | 30                   | 30                 | 30                    | BOTH             | HTML         | 0                        |                       | 0                  |                          |              | 0                            |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF SECURIT5 | Output Document new version PDF SECURITY | Output 6         |                  | TCPDF                    | 34                | Legal         | 25                  | 25                   | 25                 | 25                    | BOTH             | HTML         | 0                        |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print\|modify\|copy\|forms       |
        | 4224292655297723eb98691001100052 | Endpoint New Version Doc6         | Output Document new version solo doc     | Output 7         |                  | TCPDF                    | 0                 | Legal!@#$$$%^&| 25                  | 25                   | 25                 | 25                    | WORD             | HTML         | 0                        |                       | 1                  |                          |              | 0                            |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF7         | Output Document new version solo pdf     | Output 8         |                  | TCPDF                    | 0                 | Legal         | 25,56.98            | 25                   | 25                 | 25                    | PDF              | HTML         | 0                        |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print                            |
        | 4224292655297723eb98691001100052 | Endpoint New Version8             | Output Document new version - EndPoint   | Output 9         |                  | TCPDF                    | 1                 | Letter        | 30                  | 30,7.98              | 30                 | 30                    | BOTH             | HTML         | 0                        |                       | 0                  |                          |              | 0                            |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF SECURIT9 | Output Document new version PDF SECURITY | Output 10        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25,54.98           | 25                    | BOTH             | HTML         | 0                        |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print\|modify\|copy\|forms       |
        | 4224292655297723eb98691001100052 | Endpoint New Version Doc10        | Output Document new version solo doc     | Output 11        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25,34.09              | WORD             | HTML         | 0                        |                       | 1                  |                          |              | 0                            |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF 11       | Output Document new version solo pdf     | Output 12        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | PDtest@#$$       | HTML         | 0                        |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print                            |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF SECURI13 | Output Document new version PDF SECURITY | Output 14        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | BOTH             | HTML         | 45,988.566               |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print\|modify\|copy\|forms       |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF  15      | Output Document new version solo pdf     | Output 16        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | PDF              | HTML         | 0                        |                       | 1,99.98            |                          |              | 1                            | sample                             | sample                              | print                            |
        | 4224292655297723eb98691001100052 | Endpoint New Version Doc   18     | Output Document new version solo doc     | Output 18        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | WORD             | HTML         | 0                        |                       | 1                  |                          |              | 23454                        |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint New Version PDF SECURI22 | Output Document new version PDF SECURITY | Output 21        |                  | TCPDF                    | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | BOTH             | HTML         | 0                        |                       | 1                  |                          |              | 1                            | sample                             | sample                              | print\|modfy\|cop\|for\|aaa      |
        | 4224292655297723eb98691001100052 |                                   | Output Document old version - EndPoint   | Output 22        |                  | HTML2PDF                 | 1                 | Letter        | 30                  | 30                   | 30                 | 30                    | BOTH             | HTML         | 0                        |                       | 0                  |                          |              | 0                            |                                    |                                     |                                  |
        | 4224292655297723eb98691001100052 | Endpoint Old Version Doc          | Output Document old version solo doc     |                  |                  | HTML2PDF                 | 0                 | Legal         | 25                  | 25                   | 25                 | 25                    | WORD             | HTML         | 0                        |                       | 1                  |                          |              | 0                            |                                    |                                     |                                  |

Feature: Output Documents Resources
